/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeadmin;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author markl
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        try {
            URL imageUrl = getClass().getResource("/images/Coffee.png");
            if (imageUrl == null){
                throw new RuntimeException("Image not found! ");
            }
            ImageIcon icon = new ImageIcon(imageUrl);
            jLabel1.setIcon(icon);
        } catch (Exception e){
            jLabel1.setText("Image failed to load ");
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin = new javax.swing.JLabel();
        PasswordLBL = new javax.swing.JLabel();
        UsernameLBL = new javax.swing.JLabel();
        UsernameTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        PasswordFLD = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 405));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Admin.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Admin.setForeground(new java.awt.Color(143, 93, 70));
        Admin.setText("ADMIN LOGIN");
        getContentPane().add(Admin);
        Admin.setBounds(270, 80, 170, 32);

        PasswordLBL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        PasswordLBL.setForeground(new java.awt.Color(143, 93, 70));
        PasswordLBL.setText("Password:");
        getContentPane().add(PasswordLBL);
        PasswordLBL.setBounds(160, 210, 66, 30);

        UsernameLBL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        UsernameLBL.setForeground(new java.awt.Color(143, 93, 70));
        UsernameLBL.setText("Username:");
        getContentPane().add(UsernameLBL);
        UsernameLBL.setBounds(160, 160, 69, 30);

        UsernameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTXTActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTXT);
        UsernameTXT.setBounds(240, 160, 270, 30);

        jButton1.setBackground(new java.awt.Color(143, 93, 70));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 290, 110, 40);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(143, 93, 70));
        jCheckBox1.setText("Show Password");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(400, 250, 110, 19);

        jButton2.setBackground(new java.awt.Color(143, 93, 70));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 290, 110, 40);
        getContentPane().add(PasswordFLD);
        PasswordFLD.setBounds(240, 210, 270, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("Username = cafe admin                  Password = 12345");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 130, 250, 14);

        jLabel1.setMaximumSize(new java.awt.Dimension(720, 405));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 405));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 405);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = UsernameTXT.getText();
        String password = String.valueOf(PasswordFLD.getPassword());

        if (username.equals("cafe admin") && password.equals("12345")) {
            JOptionPane.showMessageDialog(this, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Open the new Cafe window
            MainDashboard jf2 = new MainDashboard();
            jf2.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UsernameTXT.setText("");
        PasswordFLD.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if (jCheckBox1.isSelected()) {
            PasswordFLD.setEchoChar((char) 0);
        } else {
            PasswordFLD.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JPasswordField PasswordFLD;
    private javax.swing.JLabel PasswordLBL;
    private javax.swing.JLabel UsernameLBL;
    private javax.swing.JTextField UsernameTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
